### ISSUE TITLE
will this example work for mongodb?

### ISSUE THREAD

**Issue by Radu3000** [strongloop/loopback-example-relations#1]
This example is using in-memory database.  Will it work for mongodb?

**Comment by Radu3000** [comment]
Yes it does :)!

**Comment by Radu3000** [comment]
Actually the rest interfaces work only for a single model.  When you try to get orders for a customer 1 - nothing it returned.

This is a big problem!

Can you please provide a fix.

Thanks,
Radu.

**Comment by Radu3000** [comment]
http://localhost:3000/api/Reviews/55195c13e6e28b60215e099c/author
returns Null with StatusCode = 200

**Comment by superkhau** [comment]
@Radu3000 Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by superkhau** [comment]
@Radu3000 Are you still running into issues with this?

> http://localhost:3000/api/Reviews/55195c13e6e28b60215e099c/author

Why are you querying `author` here? Am I missing something?

**Comment by Radu3000** [comment]
Simon,

I don’t have it running anymore.  But you can reproduce the steps.

**Comment by diablo2man** [comment]
I can't make this work in MongoDB. Add datasouce and change all models to this new mongodbdev datasource (datasource is verified in an empty project)

``` javascript
{
  "_meta": {
    "sources": [
      "loopback/common/models",
      "loopback/server/models",
      "../common/models",
      "./models"
    ]
  },
  "User": {
    "dataSource": "mongodbdev"
  },
  "AccessToken": {
    "dataSource": "mongodbdev",
    "public": false
  },
  "ACL": {
    "dataSource": "mongodbdev",
    "public": false
  },
  "RoleMapping": {
    "dataSource": "mongodbdev",
    "public": false
  },
  "Role": {
    "dataSource": "mongodbdev",
    "public": false
  },
  "Customer": {
    "dataSource": "mongodbdev",
    "public": true
  },
  "Review": {
    "dataSource": "mongodbdev",
    "public": true
  },
  "Order": {
    "dataSource": "mongodbdev",
    "public": true
  }
}

```

Error output:

``` shell
loopback-example-relations$ node .
/Users//Projects/loopback-example-relations/server/boot/sample-customers.js:8
    if (err) throw err;
                   ^
Error: Cannot migrate models not attached to this datasource: Customer
    at /Users//Projects/loopback-example-relations/node_modules/loopback-datasource-juggler/lib/datasource.js:794:14
    at process._tickDomainCallback (node.js:381:11)
    at process.<anonymous> (/Users//Projects/loopback-example-relations/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by superkhau** [comment]
@Radu3000 @diablo2man The example didn't work with MongoDB because of hardcoded ID values. I just provided a fix at https://github.com/strongloop/loopback-example-relations/pull/7. In addition, I added a [MongoDB branch](https://github.com/strongloop/loopback-example-relations/tree/mongodb) for you guys to test the results. It should be all working properly now.

**Comment by superkhau** [comment]
@chandadharap  Unable to set size because Waffle is bugged out, but this was a 3 pointer FYI.
