### ISSUE TITLE
Update docs to reflect example

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-example-relations#14]
Update https://docs.strongloop.com/display/LB/Creating+model+relations to follow this example.  Currently the doc is outdated.

I would like to label this "doc" but that label is not available in this repo. :-(

**Comment by superkhau** [comment]
Labels added.

**Comment by superkhau** [comment]
Connect to strongloop/loopback-example-relations/issues/14

**Comment by TrySpace** [comment]
I'd love to follow the example, but it's still outdated/not matching.

There's no `Reviews` model in the example, while on the docs it assumes it does. 

![mismatch](https://cloud.githubusercontent.com/assets/5586278/12671275/b6d15434-c66e-11e5-929e-6965c9b567a1.png)

While I'm at it, there's a lot more typos and mismatches in some of the code examples all throughout the docs. I'd guess that IBM should have enough manpower and resources to put some people on this. If they indeed want strongloop widely adopted...

**Comment by crandmck** [comment]
> ... but it's still outdated/not matching.

That's why this issue is still open.

> There's no Reviews model in the example, while on the docs it assumes it does. 

Where?  The only mention of 'Review` I see is in [Exposing REST APIs for related models](https://docs.strongloop.com/display/LB/Creating+model+relations#Creatingmodelrelations-ExposingRESTAPIsforrelatedmodels) which includes the code to create the model:

```
Review = db.createModel('review', {
    product: String,
    star: Number
  });
```

Are there other places that I'm missing?

**Comment by TrySpace** [comment]
> Where?

@crandmck https://docs.strongloop.com/display/public/LB/Tutorial%3A+model+relations#Tutorial:modelrelations-TrytheAPI

**Comment by crandmck** [comment]
OK, for the moment I transcluded the README into https://docs.strongloop.com/display/LB/Tutorial%3A+model+relations.  You should be able to follow that.
