### ISSUE TITLE
Merge embedded relations into this example

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-example-relations#17]
Per https://github.com/strongloop/loopback/issues/1758 we would like to merge [loopback-example-embedded-relations](https://github.com/strongloop/loopback-example-embedded-relations) into this repo. We want to do this to reduce the total number of example repos.

Because these two examples use different sets of models, this won't be trivial, but it should be possible to do with a bit of thought.  @jannyHou If you have questions about how to proceed, please ping me or @superkhau .

**Comment by jannyHou** [comment]
@crandmck Thanks, let me try it!

**Comment by jannyHou** [comment]
it will be merged in this pr
https://github.com/strongloop/loopback-example-relations/pull/20

**Comment by bajtos** [comment]
Closing as done since #20 has been already landed.

**Comment by superkhau** [comment]
@jannyHou Please deprecate the old repo (loopback-example-embedded-relations).

**Comment by jannyHou** [comment]
Thank you @superkhau I will archive it now.

**Comment by crandmck** [comment]
I went ahead and removed loopback-example-embedded-relations from https://github.com/strongloop/loopback-example.

**Comment by superkhau** [comment]
@crandmck TY
