### ISSUE TITLE
what visual tools are available to build relationships like in docs

### ISSUE THREAD

**Issue by Radu3000** [strongloop/loopback-example-relations#2]
reading http://docs.strongloop.com/display/public/LB/BelongsTo+relations

i see snapshots of relationships - example: Order to Customer.  Are you using some kind of visual tool instead of command line (slc loopback:relation)?

If so could you please share.

Thanks,
Radu

**Comment by superkhau** [comment]
Do you mean build the graphics or the relationship code generation?

**Comment by Radu3000** [comment]
i meant:
1. visually design the relationships (i.e. graphics) in some IDE tool
2. transform the visual model to a loopback model with relationship (i.e. code generation)

**Comment by superkhau** [comment]
Have you seen [`strong-arc`](https://github.com/strongloop/strong-arc)? I don't think it supports graphical representations for relations, but you are free to submit feature requests there. It does however, support code generation for relations out-of-box. Create an issue there and I'm sure @seanbrookes can give you more insight.
