### ISSUE TITLE
Polymorphic Relations examples needed

### ISSUE THREAD

**Issue by DragonTorus** [strongloop/loopback-example-relations#30]
Can you please add polymorphic relations exampes (in mode and if possible in code) for:
- HasMany polymorphic relations
- BelongsTo polymorphic relations
- HasAndBelongsToMany polymorphic relations
- HasOne polymorphic relations

It is an issue not related to functionality, but to lack of documentation& examples. If it is not a place for such issues please move it.
Thanks

**Comment by jannyHou** [comment]
@DragonTorus thanks for your suggestion, nice idea, I will add polymorphic examples then!

**Comment by jannyHou** [comment]
The branch is created for polymorphic examples, please check https://github.com/strongloop/loopback-example-relations/tree/example/polymorphic-relations

I am closing this story.
