### ISSUE TITLE
start-server script in test folder

### ISSUE THREAD

**Issue by sanandrea** [strongloop/loopback-example-relations#35]
I would really appreciate if one could explain how the test/start-server.js script works.

**Comment by superkhau** [comment]
Please ask questions using the correct channel. See https://github.com/strongloop/loopback/wiki/Questions.

That said, the script basically checks if the app has loaded properly and starts the LoopBack app once everything is ready. You'll have to dig through the source code for details.

**Comment by sanandrea** [comment]
Thanks and sorry, for posting here

**Comment by superkhau** [comment]
@sanandrea No problem, welcome to the community. ;) You'll find a lot of help in the suggested channels. If you need an immediate answer, there are many LoopBack users hanging out on Gitter. Good luck. :four_leaf_clover:

**Comment by sanandrea** [comment]
I would like to open an issue regarding start-server script :) please take a look at this: http://stackoverflow.com/questions/38313338/loopback-and-mocha-wait-for-server-to-finish-boot-scripts

**Comment by superkhau** [comment]
See https://github.com/strongloop/loopback/wiki/Reporting-issues

**Comment by superkhau** [comment]
Check the [booted event emitted by loopback-boot](https://github.com/strongloop/loopback-boot/blob/5eaa9090068ea99676ca081fc177e2a877ef9337/lib/executor.js#L61)
