### ISSUE TITLE
Related models POST/GET questions

### ISSUE THREAD

**Issue by josiahwong** [strongloop/loopback-example-relations#4]
Hi,

I was able to successfully create a HasMany relationship between two models and view the REST  calls in the Explorer view.  However, when getting or posting to the parent model, the child model is not returned as part of the json payload.  So my questions are:
1) I was able to follow the sample code to add a scope to include the child model as part of the parent in the GET call, but what is the best way to POST child data in one call with the parent?
For example:
API call to GET/POST to the parent - https://localhost:3000/api/households
API call to GET/POST to the child - https://localhost:3000/api/households/1/cars
API call to GET to a scope of the parent including the child: https://localhost:3000/api/households/propertyinfo

The propertyinfo scope code looks like:
module.exports = function(app) {
  var Household = app.models.household;
  Household.scope("propertyinfo", {include: ['cars']});
};

What should the POST code look like?

2) Is there a simpler way to POST/GET the child model as part of the parent without using scope or filter?  Ideally, the consumer of the API will not need to know my model structure.

Thanks for the help.  Sorry for the newbie question!
Josiah

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

**Comment by superkhau** [comment]
See the include filter http://docs.strongloop.com/display/LB/Include+filter
