### ISSUE TITLE
how to query relations

### ISSUE THREAD

**Issue by sciutand** [strongloop/loopback-example-relations#5]
First of all sorry to create an issue for this. I've been searching quite a bit but couldn't find much literature around querying related models in you documentation or the net.

I can't seem to find any way to query based on relations properties.
given the example.
### House Model

```
id
description
ownerId
```
### Owner Model

```
id
name
age
```

suppose I want to find all Houses where the owner.age > 50
I can't seem to be able to accomplish this simple task in one query. I can see that there are work arounds such as first getting the ownerId and then execute another request but this seems to be a major limitation. The entire framework looks pretty advanced so I'm not sure I'm missing something or there are strategies to implement to achieve such a simple task.

**Comment by superkhau** [comment]
Please post questions at https://groups.google.com/forum/#!forum/loopbackjs. See https://github.com/strongloop/loopback/wiki/Reporting-issues#question for more details.

Assuming you have your relations set up properly, you can access your `Owner` model via `House.Owner`, meaning you can do things like `House.Owner.find({where: ...`. Try it out and let me know if it works for you.
