### ISSUE TITLE
Relations with mongodb data-source not displaying

### ISSUE THREAD

**Issue by b-barry** [strongloop/loopback-example-relations#6]
Hello,

I tested the sample with in-memory datasource, everything works very well.
However, when I changed  "db" datasource connector to mongo db , the relations are not displayed.
I got a empty array when I called the sample url provided.
I tried to create a new data source, updated the data source of each model but I got a Error:
"Cannot migrate models not attached to this datasource : Customer".

The automigrate fails. Into my model-config.json, the model are binded to the good data-sources

Thanks you for your helps

**Comment by superkhau** [comment]
Can you provide a link to a test project on Github? See https://github.com/strongloop/loopback/wiki/Issues#bug-report

**Comment by b-barry** [comment]
Hello,

I created a new project and everything works fine;
Thank you for your reply
