### ISSUE TITLE
Upgrading LB Explorer leads to Swagger UI issue

### ISSUE THREAD

**Issue by crandmck** [strongloop/loopback-example-relations#9]
Upgrading app per https://github.com/strongloop-internal/scrum-loopback/issues/495 causes LB Explorer not to work properly.  There seems to be some kind of issue with Swagger UI.  I suspect it's something on the server side causing the issue, though it manifests through client JS error:
![swagger-ui-error](https://cloud.githubusercontent.com/assets/2925364/10088122/603bf3e0-62cd-11e5-8802-5757c9b675d1.png)

To reproduce, check out:
https://github.com/strongloop/loopback-example-relations/tree/upgrade-explorer

**Comment by crandmck** [comment]
@hacksparrow can you take a look at this?  What did I do wrong?

This is also happening in https://github.com/strongloop/loopback-example-access-control/tree/upgrade-explorer. 
@bajtos Is this actually an issue with the new `loopback-explorer`?  
Or am I doing something wrong?

**Comment by hacksparrow** [comment]
@crandmck I don't have access to strongloop-internal/scrum-loopback#495.

**Comment by hacksparrow** [comment]
I don't get that error on the **upgrade-explorer** branch of `git@github.com:strongloop/loopback-example-relations.git`, with the last commit:

```
commit f34010eef3f3e45274414e9e60407b27860eb1ec
Author: crandmck <rand@strongloop.com>
Date:   Thu Sep 24 15:00:57 2015 -0700

    Upgrade LB Explorer and related changes.
```

<img width="1278" alt="screen shot 2015-09-25 at 2 52 59 pm" src="https://cloud.githubusercontent.com/assets/950112/10097194/0fc17700-6395-11e5-8cf7-508787ae5613.png">

Could it be a browser-specific thing? I tested on Chrome 45.0.2454.101 and Firefox 41.0 on OS X 10.10.5, it's all good.

**Comment by crandmck** [comment]
Weird--I'm using Chrome 45.0.2454.101 on OS X.

However, when I deleted `node_modules` and did `npm install`, the problem went away, so I presume it was a transient issue.
